# Generated by Django 3.0 on 2020-02-26 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('alma_id', models.AutoField(help_text='Id del almacen', primary_key=True, serialize=False)),
                ('alma_nom', models.CharField(help_text='Nombre del almacen', max_length=45)),
                ('alma_tipo', models.CharField(help_text='Tipo del almacen', max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
                'db_table': 't_almacen',
            },
        ),
        migrations.CreateModel(
            name='CabeceraDocumento',
            fields=[
                ('doc_id', models.AutoField(help_text='Id de la cabecera', primary_key=True, serialize=False)),
                ('doc_tipo', models.CharField(help_text='Tipo de documento', max_length=45)),
                ('doc_fecha', models.DateField(help_text='Fecha de la cabecera')),
                ('doc_total', models.DecimalField(decimal_places=2, help_text='Total de pago', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Cabeceras Documento',
                'db_table': 't_cabDocumento',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('grup_id', models.AutoField(help_text='Id de la categoria', primary_key=True, serialize=False)),
                ('grup_nom', models.CharField(help_text='Descripcion de la categoria', max_length=45, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Grupos',
                'db_table': 't_grupo',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prov_id', models.AutoField(help_text='Id del proveedor', primary_key=True, serialize=False)),
                ('prov_raz_soc', models.CharField(help_text='Razon social del proveedor', max_length=45)),
                ('prov_doc', models.CharField(help_text='Documento del proveedor', max_length=20)),
                ('prov_fono', models.CharField(help_text='Telefono del proveedor', max_length=40)),
                ('prov_correo', models.CharField(help_text='Correo del proveedor', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 't_proveedor',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('um_id', models.AutoField(help_text='Id de la unidad de medida', primary_key=True, serialize=False)),
                ('um_desc', models.CharField(help_text='Descripcion de la unidad de medida', max_length=45, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Unidad de Medidas',
                'db_table': 't_um',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.AutoField(help_text='Id del usuario', primary_key=True, serialize=False)),
                ('usu_nom', models.CharField(help_text='Nombre del usuario', max_length=45)),
                ('usu_ape', models.CharField(help_text='Apellido del usuario', max_length=45)),
                ('usu_doc', models.CharField(help_text='Documento del usuario', max_length=45)),
                ('usu_correo', models.CharField(help_text='Correo del usuario', max_length=45)),
                ('usu_tipo', models.IntegerField(help_text='Tipo de usuario')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 't_usuario',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(help_text='Id del producto', primary_key=True, serialize=False)),
                ('prod_nom', models.CharField(help_text='Nombre del producto', max_length=45)),
                ('prod_prec', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=5)),
                ('grup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.Grupo')),
                ('um_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.UnidadMedida')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 't_producto',
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('precio_id', models.AutoField(help_text='Id del precio', primary_key=True, serialize=False)),
                ('precio_promo', models.DecimalField(decimal_places=2, help_text='Precio promocion', max_digits=5)),
                ('precio_fechin', models.DateField()),
                ('precio_fechfin', models.DateField()),
                ('precio_est', models.BooleanField(default=False, help_text='Estado del precio en oferta')),
                ('precio_fijo', models.DecimalField(decimal_places=2, help_text='Precio fijo', max_digits=5)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.Producto')),
            ],
            options={
                'verbose_name_plural': 'Precios',
                'db_table': 't_precio',
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('ma_id', models.AutoField(help_text='Id del Movimiento del Almacen', primary_key=True, serialize=False)),
                ('ma_operacion', models.CharField(help_text='Operacion del almacen', max_length=45)),
                ('ma_cant', models.IntegerField(help_text='Cantidad del producto en el almacen')),
                ('alma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.Almacen')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.Producto')),
            ],
            options={
                'verbose_name_plural': 'Movimientos Almacen',
                'db_table': 't_movimiento_alma',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('lote_id', models.AutoField(help_text='Id del lote', primary_key=True, serialize=False)),
                ('lote_fv', models.DateField(help_text='Fecha de vencimiento del lote')),
                ('lote_pc', models.DecimalField(decimal_places=2, help_text='Precio de compra del lote', max_digits=5)),
                ('lote_cant', models.IntegerField(help_text='Cantidad del lote')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.Producto')),
                ('prov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Lotes',
                'db_table': 't_lote',
            },
        ),
        migrations.CreateModel(
            name='DetalleDocumento',
            fields=[
                ('detalle_id', models.AutoField(help_text='Id del detalle', primary_key=True, serialize=False)),
                ('detalle_cant', models.IntegerField(help_text='Cantidad del producto')),
                ('detalle_precio', models.DecimalField(decimal_places=2, help_text='Precio del detalle', max_digits=5)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.CabeceraDocumento')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.Producto')),
            ],
            options={
                'verbose_name_plural': 'Detalles Documento',
                'db_table': 't_detDocumento',
            },
        ),
        migrations.AddField(
            model_name='cabeceradocumento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='minimarket.Usuario'),
        ),
        migrations.AddField(
            model_name='cabeceradocumento',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.Usuario'),
        ),
    ]
