# Generated by Django 3.0 on 2020-02-27 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_padre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minimarket.Producto'),
            preserve_default=False,
        ),
    ]
