# Generated by Django 3.0 on 2020-02-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0002_producto_producto_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='grup_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='minimarket.Grupo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='um_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='minimarket.UnidadMedida'),
        ),
    ]
