# Generated by Django 3.0 on 2020-02-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0003_auto_20200227_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'ordering': ['um_desc'], 'verbose_name_plural': 'Unidad de Medidas'},
        ),
    ]
