# Generated by Django 3.0 on 2020-03-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0004_auto_20200227_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minimarket.Producto'),
        ),
    ]
