# Generated by Django 3.0 on 2020-03-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0006_auto_20200307_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='prod_nom',
            new_name='nombre_producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(db_column='prod_nom', help_text='Nombre del producto', max_length=45),
        ),
    ]
