# Generated by Django 3.0 on 2020-03-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0007_auto_20200307_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='grup_id',
            field=models.ForeignKey(db_column='grup_id', on_delete=django.db.models.deletion.PROTECT, to='minimarket.Grupo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_padre',
            field=models.ForeignKey(db_column='producto_padre', null=True, on_delete=django.db.models.deletion.CASCADE, to='minimarket.Producto'),
        ),
    ]
