# Generated by Django 3.0 on 2020-03-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0009_auto_20200307_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado_del_producto',
            field=models.BooleanField(db_column='prod_est', default=True, help_text='Estado del producto'),
        ),
    ]
