# crar una base datos SI NO EXISTE y si EXISTE la BD
# ya no la va a crear
create database if not exists codigo9;
use codigo9;
# CREAR UNA TABLA DEPARTAMENTOS CON DEP_ID INT, DEP_NOM 
# VARCHAR(100) y una tabla EMPLEADOS  con su EMP_ID INT, EMP_NOMBRE VARCHAR(50)
# ID_DEP INT y una relacion de uno a muchos entre DEPARTAMENTO CON EMPLEADOS
# CTRL+B => IDENTAR PERO NO IMPLICA EN SU FUNCIONAMIENTO
CREATE TABLE DEPARTAMENTOS (
    DEP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DEP_NOM VARCHAR(100)
);
CREATE TABLE EMPLEADOS (
	EMP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMP_NOMBRE VARCHAR(50),
    ID_DEP INT ,
    FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTOS(DEP_ID)
);
INSERT INTO DEPARTAMENTOS (DEP_NOM) VALUES ("FINANZAS"),("MARKETING");

INSERT INTO DEPARTAMENTOS (DEP_NOM) VALUES ("ADMINISTRACION"),("SISTEMAS");
INSERT INTO EMPLEADOS (EMP_NOMBRE, ID_DEP) VALUES 
("EDUARDO",1),
("MARIA",2),
("RODRIGO",3),
("JUAN",1),
("JEAN",null),
("ROSARIO",3);

# INNER JOIN
# HACE QUE SIEMPRE Y CUANDO HAYA UNA INTERSECCION ENTRE DOS O MAS TABLAS DEVUELVA
# SU RESULTADO
# SOLAMENTE PONER JOIN SE SOBRE ENTIENDE QUE ES UN INNER JOIN
SELECT * FROM DEPARTAMENTOS INNER JOIN 
EMPLEADOS ON DEPARTAMENTOS.DEP_ID = EMPLEADOS.ID_DEP;

# TAMBIEN SE PUEDE USAR ALIAS EN LAS TABLAS PARA HACER MAS CORTA LA COMPARACION 
# CON LOS JOINS
SELECT D.DEP_NOM,E.EMP_NOMBRE FROM DEPARTAMENTOS AS D INNER JOIN 
EMPLEADOS AS E ON D.DEP_ID = E.ID_DEP;

# SELECCIONE TODOS LOS CAMPOS DE MI TABLA EMPLEADOS QUE TENGA EN COMUN CON MI
# TABLA DEPARTAMENTOS
SELECT E.* FROM DEPARTAMENTOS AS D INNER JOIN EMPLEADOS AS E ON D.DEP_ID = E.ID_DEP;

# LEFT JOIN
# TRAE TODO EL UNIVERSO A (EMPLEADOS) Y SI TIENE O NO TIENE INTERSECION CON EL
# UNIVERSO B LO MUESTRA PERO SI EL UNIVERSO B NO TIENE ALGO EN COMUN CON EL 
# UNIVERSO A NO LO MUESTRA
SELECT * FROM EMPLEADOS AS E LEFT JOIN DEPARTAMENTOS AS D ON E.ID_DEP=D.DEP_ID;
SELECT * FROM DEPARTAMENTOS AS D LEFT JOIN EMPLEADOS AS E ON E.ID_DEP=D.DEP_ID;

# RIGHT JOIN
SELECT * FROM EMPLEADOS AS E RIGHT JOIN DEPARTAMENTOS AS D ON E.ID_DEP=D.DEP_ID;

# FULL OUTER JOIN
SELECT * FROM EMPLEADOS AS E LEFT JOIN DEPARTAMENTOS AS D ON E.ID_DEP=D.DEP_ID 
UNION
SELECT * FROM EMPLEADOS AS E RIGHT JOIN DEPARTAMENTOS AS D ON E.ID_DEP=D.DEP_ID;