# Generated by Django 3.0 on 2020-02-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id_categoria', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_categoria',
            },
        ),
    ]
