# Generated by Django 3.0.4 on 2020-03-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(db_column='res_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='res_nom', max_length=40)),
                ('direccion', models.CharField(db_column='res_dir', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Restaurantes',
                'db_table': 't_restaurante',
            },
        ),
    ]
