# Generated by Django 3.0.4 on 2020-03-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20200309_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(db_column='hor_id', primary_key=True, serialize=False)),
                ('apertura', models.TimeField(db_column='hor_ape')),
                ('cierre', models.TimeField(db_column='hor_cie')),
                ('dia', models.DateField(db_column='hor_dia')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='administracion.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Horarios',
                'db_table': 't_horario',
            },
        ),
    ]
