# Generated by Django 3.0.4 on 2020-03-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20200310_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='aniversario',
            field=models.DateField(db_column='suc_aniv', default='2020-02-15'),
        ),
    ]
