# Generated by Django 3.0.4 on 2020-03-12 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0006_horario_aniversario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='prod_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='prod_nom', max_length=45)),
                ('codigo', models.CharField(db_column='prod_cod', max_length=45)),
                ('precio', models.DecimalField(db_column='prod_prec', decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(db_column='prod_desc')),
                ('imagen', models.TextField(db_column='prod_img')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 't_producto',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(db_column='serv_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='serv_nom', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
                'db_table': 't_servicio',
            },
        ),
        migrations.CreateModel(
            name='SucursalServicio',
            fields=[
                ('id', models.AutoField(db_column='sucserv_id', primary_key=True, serialize=False)),
                ('servicio', models.ForeignKey(db_column='serv_id', on_delete=django.db.models.deletion.PROTECT, related_name='sucserv_servicios', to='administracion.Servicio')),
                ('sucursal', models.ForeignKey(db_column='suc_id', on_delete=django.db.models.deletion.PROTECT, related_name='sucserv_sucursales', to='administracion.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Sucursales Servicios',
                'db_table': 't_suc_serv',
            },
        ),
        migrations.CreateModel(
            name='ProductoSucursal',
            fields=[
                ('id', models.AutoField(db_column='prod_suc_id', primary_key=True, serialize=False)),
                ('estado', models.BooleanField(db_column='prod_suc_est', default=True)),
                ('precio', models.DecimalField(db_column='prod_suc_prec', decimal_places=2, max_digits=5)),
                ('producto', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='administracion.Producto')),
                ('sucursal', models.ForeignKey(db_column='suc_id', on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='administracion.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Productos Sucursales',
                'db_table': 't_prod_suc',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(db_column='cal_id', primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField(db_column='cal_puntaje')),
                ('comentario', models.CharField(db_column='cal_coment', max_length=45)),
                ('calificacion', models.ForeignKey(db_column='cal_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='administracion.Calificacion')),
                ('sucursal', models.ForeignKey(db_column='suc_id', on_delete=django.db.models.deletion.PROTECT, related_name='cal_sucursales', to='administracion.Sucursal')),
                ('usuario', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, related_name='cal_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
                'db_table': 't_calificacion',
            },
        ),
    ]
